version: '3'
services:
  # Vault
  vault:
    hostname: vault
    image: arti.dev.cray.com/third-party-docker-stable-local/vault:1.5.5
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=hms
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
  # The KV enabler comes from:
  # https://github.com/Cray-HPE/hms-redfish-translation-layer/blob/master/vault-kv-enabler.dockerfile
  vault-kv-enabler:
    image: artifactory.algol60.net/csm-docker/stable/vault-kv-enabler:1.13.4
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - KV_STORES=hms-creds
    depends_on:
      - vault

  # HSM
  zookeeper:
    image: arti.dev.cray.com/third-party-docker-stable-local/confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: arti.dev.cray.com/third-party-docker-stable-local/confluentinc/cp-kafka:6.1.1
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  hmsds-postgres:
    hostname: hmsds-postgres
    image: arti.dev.cray.com/third-party-docker-stable-local/postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=hmsdsuser
      - POSTGRES_USER=hmsdsuser
      - POSTGRES_DB=hmsds
  cray-smd-init:
    image: artifactory.algol60.net/csm-docker/stable/cray-smd:1.30.9
    command: ["smd-init"]
    entrypoint: ["/entrypoint.sh"]
    environment:
      - SMD_DBHOST=hmsds-postgres
      - POSTGRES_HOST=hmsds-postgres
      - POSTGRES_PORT=5432
    depends_on:
      - hmsds-postgres
  cray-smd:
    image: artifactory.algol60.net/csm-docker/stable/cray-smd:1.30.9
    environment:
      - POSTGRES_HOST=hmsds-postgres
      - POSTGRES_PORT=5432
      - RF_MSG_HOST=kafka:9092:cray-dmtf-resource-event
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
      - SMD_WVAULT=true
      - SMD_RVAULT=true
    hostname: cray-smd
    depends_on:
      - cray-smd-init
      - vault
    ports:
      - "27779:27779"


  hms-hmcollector:
    build: .
    environment:
      - LOG_LEVEL=INFO
      - KAFKA_HOST=kafka
      - KAFKA_BROKERS_CONFIG=/configs/kafka_brokers-local.json
      - SM_URL=http://cray-smd:27779
      - POLLING_ENABLED=true
      - RF_SUBSCRIBE_ENABLED=true
      - VAULT_TOKEN=hms
      - CRAY_VAULT_JWT_FILE=configs/token
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - VAULT_ADDR=http://vault:8200
      - VAULT_KEYPATH=hms-creds
    depends_on:
      - kafka
      - vault
    ports:
      - "80:80"
    volumes:
      - ./configs:/configs