apiVersion: apps/v1
kind: Deployment
metadata:
  name: cray-hms-hmcollector
  labels:
    app.kubernetes.io/name: cray-hms-hmcollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cray-hms-hmcollector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cray-hms-hmcollector
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "8082,9092,2181"
    spec:
      containers:
        - name: cray-hms-hmcollector
          image: "{{ include "cray-hms-hmcollector.image-prefix" . }}cray/hms-hmcollector:{{ include "cray-hms-hmcollector.imageTag" . }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.collectorConfig.logLevel}}"

            - name: POLLING_ENABLED
              value: "{{ .Values.collectorConfig.pollingEnabled }}"
            - name: POLLING_INTERVAL
              value: "{{ .Values.collectorConfig.pollingInterval }}"

            - name: RF_SUBSCRIBE_ENABLED
              value: "{{ .Values.collectorConfig.redfishSubscribeEnabled }}"
            - name: RF_STREAMING_ENABLED
              value: "{{ .Values.collectorConfig.redfishStreamingEnabled }}"
            - name: REST_ENABLED
              value: "{{ .Values.collectorConfig.restEnabled }}"

            - name: HSM_REFRESH_INTERVAL
              value: "{{ .Values.collectorConfig.hsmRefreshInterval }}"
            - name: SM_URL
              value: "http://cray-smd"

            - name: REST_URL
              value: "http://{{ .Values.hmcollector_external_ip }}"

            - name: VAULT_ENABLED
              value: "{{ .Values.collectorConfig.vaultEnabled }}"
            - name: VAULT_ADDR
              value: "http://cray-vault.vault:8200"
            - name: VAULT_SKIP_VERIFY
              value: "true"
            - name: VAULT_KEYPATH
              value: "secret/hms-creds"
            - name: HMCOLLECTOR_CA_URI
              value: "{{ .Values.hms_ca_uri }}"
#            - name: HMCOLLECTOR_LOG_INSECURE_FAILOVER
#              value: true
          ports:
            - containerPort: 80
              name: hmc-insecure
            - containerPort: 443
              name: hmc-secure
          livenessProbe:
            httpGet:
              path: /liveness
              port: hmc-insecure
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readiness
              port: hmc-insecure
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: hms-hmcollector-kafka-brokers
              mountPath: /configs/kafka_brokers.json
              readOnly: true
              subPath: kafka_brokers.json
            - name: cray-pki-cacert-vol
              mountPath: /usr/local/cray-pki
          resources:
            limits:
              cpu: "4"
              memory: 5Gi
            requests:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: hms-hmcollector-kafka-brokers
          configMap:
            name: hms-hmcollector-kafka-brokers
        - name: cray-pki-cacert-vol
          configMap:
            name: cray-configmap-ca-public-key
